name: Build Images

on: [push, workflow_dispatch]

jobs:
  build-debian-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        cd $GITHUB_WORKSPACE
        nix --version
        ls
