name: Build Images

on: [push, workflow_dispatch]

jobs:
  build-debian-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2.1.0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: setup environment
      run: |
        nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
        nix-channel --update
        export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
        nix-shell '<home-manager>' -A install
        home-manager init
        rm -rf /home/runner/home-manager/home.nix
        cp $GITHUB_WORKSPACE/github-actions/builder-home/home-manager/home.nix ~/.config/home-manager/home.nix
        home-manager switch
        exit 0

